[supervisord]
logfile=/Users/aatifquamre/masterbot/config/supervisord.log
pidfile=/Users/aatifquamre/masterbot/config/supervisord.pid
nodaemon=false

[unix_http_server]
file=/Users/aatifquamre/masterbot/config/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///Users/aatifquamre/masterbot/config/supervisor.sock
